### PR TITLE
Feat/githubPullRequests

### PR DESCRIPTION
**Pull request by kishore03109**
## Problem 
Tooling wan closed PR reviews once per 3 months. This is a jank PR done quickly get this up.

## Reviewer notes
I am not sure if this belongs here, I am ok to not merge it too. I just want a point of reference for future ops/pm to be able to run this and get a number to report. open to feedback on this. 

## Tests
after running should see this at the end
Screenshot 2023-07-14 at 10 48 41 AM

### CODE REVIEW

**Comment by seaerchin** [comment]
Thanks for this! Actually, could we do raise this PR in our infra folder (for lambda functions) + have event bridge scheduler?

**Comment by kishore03109** [comment]
@seaerchin Good idea! 
I think since tooling is not so sure about how often they need this/is this metric something that they value, lets defer this effort until they get back to us on this

**Comment by seaerchin** [comment]
> @seaerchin Good idea! I think since tooling is not so sure about how often they need this/is this metric something that they value, lets defer this effort until they get back to us on this

as in i just want the PR to be made to infra repo (as-is, no extra effort) cos idt engineers will think to look in `conversion-scripts` for this. 

the event bridge/lambda etc can all be done next time

**Review by harishv7 — COMMENTED** [review]
are we moving this script to infra repo? actually shouldn't this script be in our isomer-tooling repo?

**Comment by kishore03109** [comment]
@seaerchin @harishv7 ya I am more in favour of moving this into the tooling repo. chin, let me know if you have any concerns here ya

**Comment by kishore03109** [comment]
moved this to [isomer/tooling](https://github.com/isomerpages/isomer-tooling/pull/45)

**Pull request closed without merging**
